/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controlador;

import java.awt.GridLayout;
import java.awt.event.*;
import java.util.LinkedList;
import javax.swing.*;
/**
 *
 * @author HP
 */
public class DialogAñadeAristas extends JDialog {

    
    private JButton bAceptar = new JButton("Aceptar");
    private JButton bOtroPto = new JButton("Otro Punto");
    
    private LinkedList<JTextField> camposTexto= new LinkedList<JTextField>();
    private LinkedList<JLabel> etiquetas = new LinkedList<JLabel>();
    
    private int [] puntos = null;
    /**
     * Creates new form DialogAñadeAristas
     */
    public DialogAñadeAristas(JFrame owner) {
//        super(parent, modal);
//        initComponents();
        super(owner,"Introduce aristas", true);
        
        setLayout(new GridLayout(0, 2));
        
        camposTexto.add(new JTextField());
        etiquetas.add(new JLabel("Punto 0"));
        camposTexto.add(new JTextField());
        etiquetas.add(new JLabel("Punto 1"));
        
        add(bAceptar);
        add(bOtroPto);
        add(etiquetas.get(0));
        add(camposTexto.get(0));
        add(etiquetas.get(1));
        add(camposTexto.get(1));
        
        bAceptar.addActionListener(new ManejadorBotonAceptar());
        bOtroPto.addActionListener(new ManejadorBotonOtroPunto());
        
        pack();
        setResizable(false);
    }

    public int [] muestra(){
        puntos=null;
        setVisible(true);
        
        while(camposTexto.size()>2){
            remove(camposTexto.removeLast());
            remove(etiquetas.removeLast());
        }
        pack();
        return puntos;
    }
    private class ManejadorBotonAceptar implements ActionListener{
        public void actionPerformed(ActionEvent e){
            puntos = new int[camposTexto.size()];
            int i =0;
            try {
                for (i = 0; i <camposTexto.size();i++) 
                   puntos[i]=Integer.parseInt(camposTexto.get(i).getText());
                   
                
            } catch (NumberFormatException except) {
                puntos=null;
                JOptionPane.showMessageDialog(null,"Error en punto" +i, "Error en los Datos", JOptionPane.ERROR_MESSAGE);
                return;
                
            }
            setVisible(false);
        }
    }
    private class ManejadorBotonOtroPunto implements ActionListener{
        
        public void actionPerformed(ActionEvent e){
            JLabel l = new JLabel("Punto "+camposTexto.size());
            etiquetas.add(l);
            add(l);
            JTextField tf= new JTextField();
            camposTexto.add(tf);
            add(tf);
            pack();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DialogAñadeAristas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DialogAñadeAristas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DialogAñadeAristas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DialogAñadeAristas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DialogAñadeAristas dialog = new DialogAñadeAristas(new JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
