/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controlador;

import java.awt.*;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class PanelPuntos extends javax.swing.JPanel {

    private Puntos puntos;
    private Aristas aristas;
    
    
    /**
     * Creates new form PanelPuntos
     */
    public PanelPuntos(Puntos puntos, Aristas aristas) {
        initComponents();
        this.puntos=puntos;
        this.aristas=aristas;
        setPreferredSize(new Dimension(400,400));
        setBackground(Color.LIGHT_GRAY);
        
    }
    public void painComponent(Graphics g){
        super.paintComponent(g);
        
        int i=0;
        Punto p ;
        while((p= puntos.punto(i))!=null){
            g.drawString(String.valueOf(i), p.x, p.y);
            i++;
        }
        i=0;
        Arista a;
        while((a= aristas.artista(i))!=null){
        g.drawLine(a.ptoIni.x, a.ptoIni.y, a.ptoFin.x, a.ptoFin.y);
            i++;
    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
